config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] do
    resources :items
  end

  

  get 'welcome/index'
  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  scope :visible_to, -> (user) { user ? all : where(@items.user = @user) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  private
    def require_sign_in
     unless current_user
       flash[:alert] = "You must be logged in to do that"
       redirect_to new_session_path
     end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    
    if @item.save
      flash[:notice] = "Item was saved successfully."
      redirect_to @item
    else
      flash.now[:alert] = "There was an error saving the item. Please try again."
      render :new
    end
  end
  def index
    @items = Item.all
  end
  def new
    @item = Item.new
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def destroy
    @item = Item.find(params[:id])
 
    if @item.destroy
      flash.now[:alert] = "\"#{@item.name}\" was deleted successfully."
    else
      flash.now[:alert] = "There was an error deleting the item."
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  private
  def item_params
     params.require(:item).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      create_session(user)
      flash[:notice] = "Alright, #{user.name.capitalize}! It's time for something fun and productive"
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end
 
  def destroy
    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @user = User.new
  end
  def create
     @user = User.new
     @user.name = params[:user][:name]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]
     
     if @user.save
      flash[:notice] = "Welcome to BlocItOff #{@user.name}!"
      create_session(@user)
      redirect_to root_path
     else
       flash.now[:alert] = "There was an error creating your account. Please try again."
       render :new
     end
  end
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?

     content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
     session[:user_id] = user.id
  end

  def destroy_session(user)
     session[:user_id] = nil
  end
 
  def current_user
     User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [item] do |f| %>
   <% if item.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(item.errors.count, "error") %>.</h4>
       <ul>
         <% item.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(item.errors[:name]) do %>
     <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "What will you do today?" %>
  <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
<% end %>

app/views/items/_item.html.erb
<div class="media" id="item-<%= item.id %>">
   <div class="media-body">
     <h4 class="media-heading">
        <%= link_to "", item, method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
        <%= link_to item.name, item_path(item.id) %>
     </h4>
     <small>
        Assigned to <%= item.user.email %>
        </br>
        <% if Time.now - item.created_at >= 7.days  %>
          Overdued
        <% else %>
          <%= distance_of_time_in_words(Time.now - item.created_at, 7.days, include_seconds: true) %> left to complete
        <% end %>
        </br>
        Created at <%= item.created_at %>
     </small>
   </div>
</div>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-<%= @item.id %>').hide();
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/items/index.html.erb
<h1>All Items</h1>
<div class="row">
  <div class="col-md-8">
    <% @items.each do |item| %>
      <%= render partial: 'items/item', locals: {item: item} %>
    <% end %>
  </div>
<div class="col-md-4">
    <%= link_to "New Item", new_item_path, class: 'btn btn-success' %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>
<div class="row">
  <div class="col-md-4">
    <p>Make sure your item is:</p>
    <ul>
       <li>Specific</li>
       <li>Measurable</li>
       <li>Achievable</li>
       <li>Realistic</li>
       <li>Time-bound</li>
     </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { user: @user, item: @item } %>
  </div>
</div>

app/views/items/show.html.erb
</br>
 <div class="row">
   <div class="col-md-8">
      <%= render partial: 'items/item', locals: { item: @item } %>
   </div>
   <div class="col-md-4">
    <% if current_user %>
      <%= link_to "Edit Item", edit_item_path, class: 'btn btn-success' %>
    <% end %>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "Blocitoff", items_path %></li>
      <li><%= link_to "Kele", items_path %></li>
      <li><%= link_to "Tetriage", items_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
          <div class="pull-right">
            <%= link_to current_user.name.capitalize, user_path(current_user) %> | 
            <%= link_to "Sign Out", session_path(current_user), method: :delete %>
          </div>
        <% else %>
            <%= link_to "Sign In", new_session_path %> or
            <%= link_to "Sign Up", new_user_path %>
        <% end %>
      </div>
    </ul>
    <div class = "flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  <%= yield %>
  </div>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2>Sign up</h2>
 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/users/show.html.erb
<h2>Profile</h2>
<div class="row">
   <div class="col-md-8">
     <div class="media">
       <div class="media-body">
         <h5 class="media-heading">Name: <%= @user.name %></h5>
         <h5 class="media-heading">Email: <%= @user.email %></h5>
       </div>
     </div>
   </div>
   <div class="col-md-4">
      <%= link_to "Edit Account", edit_user_registration_path, class: 'btn btn-success' %>
   </div>
 </div>
 <div class="row">
   <div class="col-md-8">
      <h2>My Items</h2>
         <% @user.items.each do |item| %>
            <%= render partial: 'items/item', locals: {item: item} %>
         <% end %>
   </div>
 </div>
 </br>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Blocitoff</h1>
   <p>Blocitoff is the only To-Do list that actually help you complete tasks</p>
   <% if current_user %>
      Here is one of my blog showing you <%= link_to "The correct way to use to-do list!" %>
   <% else %>
      <%= link_to "Sign In", new_session_path %> or
      <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
    <% end %>
 </div>
 
 <div class="row">
   <div class="col-md-4">
     <h2>To-do List</h2>
     <p>This tool is created based on The Just Do It Scribble idea from The Happiness Equation book (Neil Pasricha)</p>
   </div>
   <div class="col-md-4">
     <h2>Kele</h2>
     <p>Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah </p>
   </div>
   <div class="col-md-4">
     <h2>Tetriage</h2>
     <p>Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah </p>
   </div>
 </div>

app/views/welcome/item.html.erb
<h1>Welcome#todo</h1>
<p>Find me in app/views/welcome/todo.html.erb</p>

app/views/welcome/todo.html.erb
<h1>Welcome#todo</h1>
<p>Find me in app/views/welcome/todo.html.erb</p>